sudo: false
language: node_js
node_js:
  - '6'

install:
  - npm install
  - cd client && npm install && cd ..

script:
  # Build MCS-Lite console (Webpack)
  - cd client && npm run build:global && cd ..

  # Build App (NW.js)
  - npm run build:global

  # Compression
  - cd ./out/mcs-lite-app
  - find . -type d -name "osx*" -maxdepth 1 -mindepth 1 -exec tar zcf {}.tar.gz {}  \;
  # - find . -type d -name "linux*" -maxdepth 1 -mindepth 1 -exec tar zcf {}.tar.gz {}  \;
  - find . -type d -name "win*" -maxdepth 1 -mindepth 1 -exec zip -rq {}.zip {}  \;
  - ls . && cd ../..

cache:
  directories:
    - node_modules
    - client/node_modules

deploy:
  provider: releases
  api_key:
    secure: Ii5Phu/1jnnXjtNbwt+FSH2CBq7Db7TXKoHoN7SrPJAs7w+J/ZDSTKf0Scbck+8woyImXTlh6pX+3qXU57u3FkigeOqX46i4OcT7SJQ+lVbgIVJRNojlw0gZmZ1hgTLWl5914xMnO82+99xjlU2amG4Cv7jkx61M8Os56pqR4kMo6uy1YkSEYNc06cZYNTkNWuGfxlCyMtz3G4WYgKEJXEqbfGJ7Hz6jWkaG+g03KuzBI1XbjNpT13VyxSkcC+xz4uaPO6ZRR5f6wKUbyGfl51xYmZkwYdqc2Zm2tfG+S1gHpyQwz9fXb5DOR5FbRWOmW+YSvbBZwELA67nxpempMT1Nx0v0sp6z8pOeJQLZKuyhMe2kRZD6nKY/feMSVC0ABnbqw4MiitgLcHMqVLpir45JuhoWqkEGU24zbu6Ut37UcrXgdcD7lXzTy2tEHptgsiRk0Y5oMMjZhRLiausD4g2cg7m4cfC4tuScEWwEXqTTScPZTrF5t0XhfOJoVwaz6x//kmx9drYbBTaWJSul4WMiVcxm9OmSxez7BKQx9Wa4i+IecbG5feFS6lKqtwL7hSbEoM9SYtof/F4QfJedE3pl43GwVNNpf+618HvNZMmwxtAXIiXzc7AAobXyT2JPOwKme9tx5ziUch7TSqZi3hnL/19cbndeb0GvuXcDHcc=
  file_glob: true
  file: './out/mcs-lite-app/*.(tar.gz,zip)'
  skip_cleanup: true
  on:
    repo: MCS-Lite/mcs-lite-app
    tags: true
